default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  prepared_statements: false
  username: postgres
  password: Ffwjgv8e
  host: localhost
  port: 5432

development:
  <<: *default
  database: url_shortener_development

test:
  <<: *default
  database: url_shortener_test

production:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>