default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  prepared_statements: false

development:
  <<: *default
  database: url_shortener_development
  username: postgres
  password: Ffwjgv8e
  host: localhost
  port: 5432

test:
  <<: *default
  database: url_shortener_test
  username: postgres
  password: Ffwjgv8e
  host: localhost
  port: 5432

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  prepared_statements: false